### ISSUE TITLE
Build fails when html-webpack-plugin is not installed

### ISSUE THREAD

**Issue by lopopolo** [brunocodutra/webapp-webpack-plugin#148]
```
▶ yarn webpack --mode production
yarn run v1.12.3
$ /Users/lopopolo/dev/repos/hyperbola/node_modules/.bin/webpack --mode production
Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (/Users/lopopolo/dev/repos/hyperbola/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports.tapHtml (/Users/lopopolo/dev/repos/hyperbola/node_modules/webapp-webpack-plugin/src/compat.js:18:29)
    at child.run.then.tags (/Users/lopopolo/dev/repos/hyperbola/node_modules/webapp-webpack-plugin/src/index.js:46:13)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Setting `inject: false` in webpack.config.js works around the failure. If `html-webpack-plugin` is a required peer dependency, can package.json flag it as such?

**Comment by brunocodutra** [comment]
Thanks for reporting, `html-webpack-plugin` is not a required peer dependency, this is a bug that needs to be fixed - the expected behavior is to automatically fallback to `inject: false` if the module isn't installed.
